# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: Wally
description: >-
  Wally is a digital backup of your physical wallet. Put your cards into Wally to keep them safe and available at all times.

url: https://wally.app
email: info@wally.app

is_app: 1

copyright_year: 2012-2024
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

instagram_username: wally.app
mastodon_username: kankoda@mastodon.social
twitter_username: thewallyapp

assets: /assets/
header_image: /assets/icon/icon-320.png
header_image_type: icon

urls:
  email: mailto:info@wally.app
  rss: https://getlicensekit.com/feed.xml

  appstore:   https://itunes.apple.com/app/wally/id516398915
  blog:       /blog
  instagram:  https://www.instagram.com/wally.app
  mastodon:   https://mastodon.social/@kankoda
  twitter: https://twitter.com/thewallyapp

header_pages:
  - index.html
  - pages/blog.md
  - pages/download.md

footer_sitemap:
  - index.html
  - pages/blog.md

footer_app:
  - pages/privacy-policy.md

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  -
    scope:
      type: "pages"
    values:
      hero: ""
  -
    scope:
      type: "posts"
    values:
      author: "danielsaidi"
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/