# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: Wally
description: >-
  Wally is a digital wallet for iPhone and iPad. Put your cards into Wally to keep them safe and available at all times.

url: https://wally.app
email: info@wally.app

is_app: 1

copyright_year: 2012-2026
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

bluesky_username: "@kankoda.bsky.social"
instagram_username: wally.app
mastodon_username: kankoda@mastodon.social
twitter_username: thewallyapp

assets: /assets/
header_image: /assets/icon/icon-header.png
header_image_type: icon
fonts: Pacifico

urls:
  email:  mailto:info@wally.app

  blog:       /blog
  rss:        /feed.xml
  privacy:    /privacy-policy
  
  appstore:   https://itunes.apple.com/app/wally/id516398915
  bluesky:    https://bsky.app/profile/kankoda.bsky.social
  instagram:  https://www.instagram.com/wally.app
  mastodon:   https://mastodon.social/@kankoda
  twitter:    https://twitter.com/thewallyapp

header:
  title: Wally
  icon: /assets/icon/header.png
  pages:
    - index.html
    - pages/blog.md
    - pages/download.md
  cta:
    title: Download
    url: https://itunes.apple.com/app/wally/id516398915

footer:
  # Sections with links defined as "Title | url" strings.
  sections:
    - title: Site
      links:
        - Home | /
        - Blog | /blog
    - title: App
      links:
        - App Store | https://itunes.apple.com/app/wally/id516398915
        - Privacy Policy | /privacy-policy
    - title: News & Press
      links:
        - Blog | /blog
        - RSS | /feed.xml
    - title: Social
      links:
        - E-mail | mailto:info@wally.app
        - Instagram | https://www.instagram.com/wally.app
    - title: Kankoda
      links:
        - Website | https://kankoda.com
        - Apps | https://kankoda.com/apps

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
      page-class: "dark"
      image: /assets/headers/website.jpg
  -
    scope:
      path: "pages/blog.md"
    values:
      image: /assets/headers/blog.jpg
  -
    scope:
      type: "posts"
    values:
      author: "danielsaidi"
      layout: "post"
      page-class: "dark"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/